import express from "express";
import abioticocoluna from "./abioticocoluna.routes";
import campanha from "./campanha.routes";
import instituicao from "./instituicao.routes";
import reservatorio from "./reservatorio.routes";
import sitio from "./sitio.routes";
import abioticosuperficie from "./abioticosuperficie.routes";
import aguamateriaorganicasedimento from "./aguamateriaorganicasedimento.routes";
import bioticocoluna from "./bioticocoluna.routes";
import bioticosuperficie from "./bioticosuperficie.routes";
import bolhas from "./bolhas.routes";
import camarasolo from "./camarasolo.routes";
import ionsnaaguaintersticialdosedimento from "./ionsnaaguaintersticialdosedimento.routes";
import medidacampocoluna from "./medidacampocoluna.routes";
import medidacamposuperficie from "./medidacamposuperficie.routes";
import nutrientessedimento from "./nutrientessedimento.routes";
import parametrosbiologicosfisicosagua from "./parametrosbiologicosfisicosagua.routes";
import pfq from "./pfq.routes";
import tabela from "./tabela.routes";
import tc from "./tc.routes";
import variaveisfisicasquimicasdaagua from "./variaveisfisicasquimicasdaagua.routes";

const router = express.Router();

router.use("/abioticocoluna", abioticocoluna);
router.use("/campanha", campanha);
router.use("/instituicao", instituicao);
router.use("/reservatorio", reservatorio);
router.use("/sitio", sitio);
router.use("/abioticosuperficie", abioticosuperficie);
router.use("/aguamateriaorganicasedimento", aguamateriaorganicasedimento);
router.use("/bioticocoluna", bioticocoluna);
router.use("/bioticosuperficie", bioticosuperficie);
router.use("/bolhas", bolhas);
router.use("/camarasolo", camarasolo);
router.use("/ionsnaaguaintersticialdosedimento", ionsnaaguaintersticialdosedimento);
router.use("/medidacampocoluna", medidacampocoluna);
router.use("/medidacamposuperficie", medidacamposuperficie);
router.use("/nutrientessedimento", nutrientessedimento);
router.use("/parametrosbiologicosfisicosagua", parametrosbiologicosfisicosagua);
router.use("/pfq", pfq);
router.use("/tabela", tabela);
router.use("/tc", tc);
router.use("/variaveisfisicasquimicasdaagua", variaveisfisicasquimicasdaagua);

export default router;
